In [30]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import csv
import requests
import json
import urllib
import io
from pprint import pprint

output_data_file = "Desktop/air.csv"

In [31]:
import requests
#list to hold zip codes
zipCode = []
KEY ="F495480F-C2BE-4278-BF64-602A33887D65"
url_c = "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=94306&API_KEY="+KEY
url_9 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-09T00-0000&distance=25&API_KEY="+KEY
url_10 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-10T00-0000&distance=25&API_KEY="+KEY
url_11 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-11T00-0000&distance=25&API_KEY="+KEY
url_12 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-12T00-0000&distance=25&API_KEY="+KEY
url_13 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-13T00-0000&distance=25&API_KEY="+KEY
url_14 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-14T00-0000&distance=25&API_KEY="+KEY
url_15 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-15T00-0000&distance=25&API_KEY="+KEY

current_response = requests.get(url_c).json()
historical_response_9 = requests.get(url_9).json()
historical_response_10 = requests.get(url_10).json()
historical_response_11 = requests.get(url_11).json()
historical_response_12 = requests.get(url_12).json()
historical_response_13 = requests.get(url_13).json()
historical_response_14 = requests.get(url_14).json()
historical_response_15 = requests.get(url_15).json()
pprint(current_response)
pprint(historical_response_9)
pprint(historical_response_10)
pprint(historical_response_11)
pprint(historical_response_12)
pprint(historical_response_13)
pprint(historical_response_14)
pprint(historical_response_15)

[{'AQI': 16,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2018-04-14 ',
  'HourObserved': 9,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'O3',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 42,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2018-04-14 ',
  'HourObserved': 9,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 40,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-09 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 35,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-10 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 31,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-11 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 126,
  'Category': {'Name': 'Unhealthy for Sensitive Groups', 'Number': 3},
  'DateObserved': '2017-10-11 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 47,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-12 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 154,
  'Category': {'Name': 'Unhealthy', 'Number': 4},
  'DateObserved': '2017-10-12 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 44,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-13 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 152,
  'Category': {'Name': 'Unhealthy', 'Number': 4},
  'DateObserved': '2017-10-13 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 38,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-14 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 78,
  'Category': {'Name': 'Moderate', 'Number': 2},
  'DateObserved': '2017-10-14 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]
[{'AQI': 58,
  'Category': {'Name': 'Moderate', 'Number': 2},
  'DateObserved': '2017-10-15 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'OZONE',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'},
 {'AQI': 40,
  'Category': {'Name': 'Good', 'Number': 1},
  'DateObserved': '2017-10-15 ',
  'HourObserved': 0,
  'Latitude': 37.48,
  'LocalTimeZone': 'PST',
  'Longitude': -122.22,
  'ParameterName': 'PM2.5',
  'ReportingArea': 'Redwood City',
  'StateCode': 'CA'}]

In [32]:
import csv

historic_data = open('Desktop/historic.csv', 'w')
csvwriter = csv.writer(historic_data)
count = 0
for historic in historical_response_9:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())
    
for historic in historical_response_10:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())

for historic in historical_response_11:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())

for historic in historical_response_12:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())

for historic in historical_response_13:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())

for historic in historical_response_14:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())

for historic in historical_response_15:
      if count == 0:
             header = historic.keys()
             csvwriter.writerow(header)
             count += 1
      csvwriter.writerow(historic.values())
historic_data.close()

historic1 = pd.read_csv('Desktop/historic.csv')
#print(historic1)
historic1


#historic_data_pd = pd.read_csv(historic_data)
#historic_data_pd

,DateObserved,HourObserved,LocalTimeZone,ReportingArea,StateCode,Latitude,Longitude,ParameterName,AQI,Category
0,2017-10-09,0,PST,Redwood City,CA,37.48,-122.22,OZONE,40,"{'Number': 1, 'Name': 'Good'}"
1,2017-10-10,0,PST,Redwood City,CA,37.48,-122.22,OZONE,35,"{'Number': 1, 'Name': 'Good'}"
2,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,OZONE,31,"{'Number': 1, 'Name': 'Good'}"
3,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,126,"{'Number': 3, 'Name': 'Unhealthy for Sensitive..."
4,2017-10-12,0,PST,Redwood City,CA,37.48,-122.22,OZONE,47,"{'Number': 1, 'Name': 'Good'}"
5,2017-10-12,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,154,"{'Number': 4, 'Name': 'Unhealthy'}"
6,2017-10-13,0,PST,Redwood City,CA,37.48,-122.22,OZONE,44,"{'Number': 1, 'Name': 'Good'}"
7,2017-10-13,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,152,"{'Number': 4, 'Name': 'Unhealthy'}"
8,2017-10-14,0,PST,Redwood City,CA,37.48,-122.22,OZONE,38,"{'Number': 1, 'Name': 'Good'}"
9,2017-10-14,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,78,"{'Number': 2, 'Name': 'Moderate'}"
10,2017-10-15,0,PST,Redwood City,CA,37.48,-122.22,OZONE,58,"{'Number': 2, 'Name': 'Moderate'}"
11,2017-10-15,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,40,"{'Number': 1, 'Name': 'Good'}"

In [33]:
historic2 = historic1.rename({'ReportingArea':'City', 'StateCode':'State', 'DateOberserved':'Date', 'HourObserved':'Hour', 'LocalTimeZone':'TimeZone', 'AQI':'AQI', 'ParameterName':'Parameter', 'Latitude':'Latitude', 'Longitude':'Longitude', 'Category':'Category'}, axis='columns')
#historic2 = historic1.rename(columns = {'ReportingArea':'City', 'StateCode':'State'})
historic2
#merge_data = historic_data.merge(zip_data, on = 'City')
#zip_data_pd.head()


#merge_data.head()
#print(merge_data)

,DateObserved,Hour,TimeZone,City,State,Latitude,Longitude,Parameter,AQI,Category
0,2017-10-09,0,PST,Redwood City,CA,37.48,-122.22,OZONE,40,"{'Number': 1, 'Name': 'Good'}"
1,2017-10-10,0,PST,Redwood City,CA,37.48,-122.22,OZONE,35,"{'Number': 1, 'Name': 'Good'}"
2,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,OZONE,31,"{'Number': 1, 'Name': 'Good'}"
3,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,126,"{'Number': 3, 'Name': 'Unhealthy for Sensitive..."
4,2017-10-12,0,PST,Redwood City,CA,37.48,-122.22,OZONE,47,"{'Number': 1, 'Name': 'Good'}"
5,2017-10-12,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,154,"{'Number': 4, 'Name': 'Unhealthy'}"
6,2017-10-13,0,PST,Redwood City,CA,37.48,-122.22,OZONE,44,"{'Number': 1, 'Name': 'Good'}"
7,2017-10-13,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,152,"{'Number': 4, 'Name': 'Unhealthy'}"
8,2017-10-14,0,PST,Redwood City,CA,37.48,-122.22,OZONE,38,"{'Number': 1, 'Name': 'Good'}"
9,2017-10-14,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,78,"{'Number': 2, 'Name': 'Moderate'}"
10,2017-10-15,0,PST,Redwood City,CA,37.48,-122.22,OZONE,58,"{'Number': 2, 'Name': 'Moderate'}"
11,2017-10-15,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,40,"{'Number': 1, 'Name': 'Good'}"

In [34]:
historic2.to_csv('Desktop/air.csv', index=True)
#print historic2.to_csv()

In [35]:
#print(zip_data)
zip_data_pd = pd.DataFrame(zip_data)
zip_data_pd.head()

,City,the_geom,ZIP,STATE,Area__,Length__
0,NAPA,MULTIPOLYGON (((-122.10329200180091 38.5132829...,94558,CA,1.231326e+10,995176.2253
1,FAIRFIELD,MULTIPOLYGON (((-121.947475002335 38.301511000...,94533,CA,9.917861e+08,200772.5566
2,DIXON,MULTIPOLYGON (((-121.65335500334429 38.3133870...,95620,CA,7.236950e+09,441860.2014
3,SONOMA,MULTIPOLYGON (((-122.406843003057 38.155681999...,95476,CA,3.001414e+09,311318.5463
4,NAPA,MULTIPOLYGON (((-122.29368500225117 38.1552379...,94559,CA,1.194302e+09,359104.6466

In [36]:
#randomly select up to 50 zip codes from Air Now API
#select 7 days (a week) during Oct 2017 (height of Sonoma fires Oct. 9 - 15)
import csv
import pandas as pd
import urllib
zip_csv = "Desktop/bayarea_zipcodes.csv"
zip_data = pd.read_csv(zip_csv)
random_zip = []
random_zip = zip_data.sample(150)
random_zip=random_zip.reset_index(drop=True)
#random_zip.ZIP
#print(random_zip)

#random_zip

In [37]:
zipCode = random_zip["ZIP"]
len(zipCode)
#print(zipCode)

150

In [38]:
zip = random_zip.set_index("City", drop = True)
#zip

In [39]:
zip_data2 = zip.loc[:, "ZIP"]
#zip["ZIP"]
zip_data2_pd = pd.DataFrame(zip_data2)
zip_data2_pd

                       ZIP
City
BERKELEY             94709
PORTOLA VALLEY       94028
MILPITAS             95035
SAN FRANCISCO        94115
OAKLAND              94618
SUNNYVALE            94087
PALO ALTO            94304
SAN LEANDRO          94578
BURLINGAME           94010
MARTINEZ             94553
SAN FRANCISCO        94130
SAN FRANCISCO        94104
CONCORD              94520
SAN ANSELMO          94960
PALO ALTO            94306
SAN FRANCISCO        94112
OAKLAND              94612
ATHERTON             94027
ALAMEDA              94502
DUBLIN               94568
NEWARK               94560
GREENBRAE            94904
SAN RAMON            94583
SOUTH SAN FRANCISCO  94080
SAN FRANCISCO        94114
OAKLAND              94613
SAN MATEO            94402
CONCORD              94519
ALVISO               95002
BERKELEY             94705
...                    ...
SAN FRANCISCO        94131
ALAMEDA              94501
HAYWARD              94542
FAIRFIELD            94533
OAKLAND              94606
ANTIOCH              94531
SAN LEANDRO          94579
RICHMOND             94805
EMERYVILLE           94608
ORINDA               94563
CLAYTON              94517
OAKLAND              94607
SAN FRANCISCO        94110
NICASIO              94946
RICHMOND             94801
SAN MATEO            94404
SUNOL                94586
SONOMA               95476
OAKLAND              94610
SAN LEANDRO          94577
SAN FRANCISCO        94122
PACIFICA             94044
OAKLAND              94619
MOSS BEACH           94038
SUNNYVALE            94085
DANVILLE             94506
SAN FRANCISCO        94129
LOS ALTOS            94022
BERKELEY             94720
SAN MATEO            94401

[150 rows x 1 columns]

In [40]:
#zip_data2_pd.to_csv('Desktop/zip_data2.csv', index=True)
zip_data2_pd.to_csv('Desktop/zip_data2.csv')

In [41]:
import pandas as pd
import csv

zip_data2 = pd.read_csv('Desktop/zip_data2.csv')
air = pd.read_csv('Desktop/air.csv')
zip_data2 = zip_data2.drop_duplicates('City')
merge_data = zip_data2.merge(air, on = 'City')
merge_data.head()

print(merge_data)

Empty DataFrame
Columns: [City, ZIP, Unnamed: 0, DateObserved, Hour, TimeZone, State, Latitude, Longitude, Parameter, AQI, Category]
Index: []

In [42]:
air2 = air.T.drop_duplicates().T
air2.head()

,Unnamed: 0,DateObserved,Hour,TimeZone,City,State,Latitude,Longitude,Parameter,AQI,Category
0,0,2017-10-09,0,PST,Redwood City,CA,37.48,-122.22,OZONE,40,"{'Number': 1, 'Name': 'Good'}"
1,1,2017-10-10,0,PST,Redwood City,CA,37.48,-122.22,OZONE,35,"{'Number': 1, 'Name': 'Good'}"
2,2,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,OZONE,31,"{'Number': 1, 'Name': 'Good'}"
3,3,2017-10-11,0,PST,Redwood City,CA,37.48,-122.22,PM2.5,126,"{'Number': 3, 'Name': 'Unhealthy for Sensitive..."
4,4,2017-10-12,0,PST,Redwood City,CA,37.48,-122.22,OZONE,47,"{'Number': 1, 'Name': 'Good'}"

In [43]:
merge_data.head()

Empty DataFrame
Columns: [City, ZIP, Unnamed: 0, DateObserved, Hour, TimeZone, State, Latitude, Longitude, Parameter, AQI, Category]
Index: []

In [44]:
print(merge_data)

Empty DataFrame
Columns: [City, ZIP, Unnamed: 0, DateObserved, Hour, TimeZone, State, Latitude, Longitude, Parameter, AQI, Category]
Index: []

In [51]:
KEY ="F495480F-C2BE-4278-BF64-602A33887D65"
base_url = f"http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&date=2017-10-09T00-0000&distance=25&API_KEY={KEY}&zipCode="
url_10 = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&zipCode=94306&date=2017-10-10T00-0000&distance=25&API_KEY="+KEY
air_data = []

record_count = 1
set_count = 1
print("testing")

for i, ZIP in enumerate(zip_data2):  #7 days x  70zipCode = 490 (Oct 9-15) Fire, use array for each date
    if (i % 70 == 0 and i >= 70):
        set_count += 1
        record_count = 0
    print(record_count, set_count)
    
    city_url = f"{base_url}{ZIP}"
    print(city_url)
    #city_url = "http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&date=2017-10-09T00-0000&distance=25&API_KEY="+KEY

    #zip_url = url + city_url
    #print(url_10)
    #print(city_url)
    #print("Processing record %s of set %s | %s" % (record_count, set_count, ReportingArea))
    print("Processing record %s of set %s | %s" % (record_count, set_count, zipCode))
    record_count += 1
    
    
    #run on APi request for each of the zipcodes
       # try:
          #  city_air = requests.get(zip_url).json()
         #   city_category = city_air[][]
          #  city_aqi = city_air[][]
          #  city_parameter = city_air[][]

testing
1 1
http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&date=2017-10-09T00-0000&distance=25&API_KEY=F495480F-C2BE-4278-BF64-602A33887D65&zipCode=City
Processing record 1 of set 1 | 0      94709
1      94028
2      95035
3      94115
4      94618
5      94087
6      94304
7      94578
8      94010
9      94553
10     94130
11     94104
12     94520
13     94960
14     94306
15     94112
16     94612
17     94027
18     94502
19     94568
20     94560
21     94904
22     94583
23     94080
24     94114
25     94613
26     94402
27     94519
28     95002
29     94705
       ...
120    94131
121    94501
122    94542
123    94533
124    94606
125    94531
126    94579
127    94805
128    94608
129    94563
130    94517
131    94607
132    94110
133    94946
134    94801
135    94404
136    94586
137    95476
138    94610
139    94577
140    94122
141    94044
142    94619
143    94038
144    94085
145    94506
146    94129
147    94022
148    94720
149    94401
Name: ZIP, Length: 150, dtype: int64
2 1
http://www.airnowapi.org/aq/observation/zipCode/historical/?format=application/json&date=2017-10-09T00-0000&distance=25&API_KEY=F495480F-C2BE-4278-BF64-602A33887D65&zipCode=ZIP
Processing record 2 of set 1 | 0      94709
1      94028
2      95035
3      94115
4      94618
5      94087
6      94304
7      94578
8      94010
9      94553
10     94130
11     94104
12     94520
13     94960
14     94306
15     94112
16     94612
17     94027
18     94502
19     94568
20     94560
21     94904
22     94583
23     94080
24     94114
25     94613
26     94402
27     94519
28     95002
29     94705
       ...
120    94131
121    94501
122    94542
123    94533
124    94606
125    94531
126    94579
127    94805
128    94608
129    94563
130    94517
131    94607
132    94110
133    94946
134    94801
135    94404
136    94586
137    95476
138    94610
139    94577
140    94122
141    94044
142    94619
143    94038
144    94085
145    94506
146    94129
147    94022
148    94720
149    94401
Name: ZIP, Length: 150, dtype: int64